---
- hosts: localhost
  
  tasks:
  - name: remove existing images
    command: docker rmi ajayprtemporary/image1
    ignore_errors: yes
  
  - name: creating docker image
    command: docker build -t ajayprtemporary/image1 .
